name: Actions Workflow
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  run-github-acions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: show dir
        run: ls
      - name: run node file
        run: node index.js
