name: Container
on: push
jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container: node:16-alpine3.12
    steps:
      - name: Log Node version
        run: |
          node -v
          cat /etc/os-release
          
      