name: Container
on: push
jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.12
    steps:
      - name: Log Node version
        run: node -v
      - name: Step with docker
        uses: docker://node:16-alpine
        with: 
          entrypoint: /bin/echo
          args: World # acts like CMD
      - name: Log Node version
        uses: docker://node:16-alpine
        with:
          entrypoint: /usr/local/bin/node
          args: -v # acts like CMD
      - uses: actions/checkout@v1
      - name: Run a Script
        uses: docker://node:16-alpine
        with:
          entrypoint: ./script.sh
          args: "Some string" # acts like CMD
  node-docker:
    runs-on: ubuntu-latest
    services:
      app: 
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports: 
          - "27017:27017"

    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get Users
        run: curl http://localhost:3001/api/users

      