name: Demo Workflow
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ls
      - run: echo "LATEST_DIR=./mydir" >> $GITHUB_ENV
      - run: echo mydir/$LATEST_DIR
      - run: cd mydir/$LATEST_DIR
  demo2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HEllo this is second job"
