name: Demo Workflow
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ls
      - run: |
          latest_directory="myDir"
          echo "Latest directory: $latest_directory"
          echo "LATEST_DIRECTORY=$latest_directory" >> $GITHUB_ENV
      - run: echo mydir/$LATEST_DIRECTORY
      - run: cd mydir/$LATEST_DIR
  demo2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HEllo this is second job"
