name: Matrix
on: push
jobs: 
  node-version:
    runs-on: ubuntu-latest
    steps: 
      - name: Log Current Node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '6'
      - name: Log node version
        run: node -v
        